/**
 * Tool types for MCP tool recommendations and definitions.
 *
 * @module types/tool
 */

/**
 * Represents a recommended MCP tool with associated metadata.
 *
 * Tool recommendations are generated by the sequential thinking process to suggest
 * appropriate tools for completing specific tasks. Each recommendation includes
 * a confidence score and rationale to help the LLM make informed decisions.
 *
 * @example
 * ```typescript
 * const recommendation: ToolRecommendation = {
 *   tool_name: 'mcp__tavily-mcp__tavily-search',
 *   confidence: 0.9,
 *   rationale: 'Best for searching current web content',
 *   priority: 1,
 *   suggested_inputs: { query: 'TypeScript documentation' },
 *   alternatives: ['mcp__web_reader__webReader']
 * };
 * ```
 *
 * NOTE: Kept as a hand-written interface (not inferred from `ToolRecommendationSchema`)
 * because `priority` is REQUIRED here but OPTIONAL in the schema (the schema accepts
 * partial input from LLMs; the normalizer fills the default). An inferred type would
 * make `priority` optional and break call sites that read it without a guard.
 */
export interface ToolRecommendation {
	/** The unique name/identifier of the recommended tool. */
	tool_name: string;

	/** Confidence score from 0-1 indicating how appropriate this tool is for the current task. */
	confidence: number;

	/** Explanation of why this tool is recommended and how it addresses the current need. */
	rationale: string;

	/** Order in the recommendation sequence (lower numbers = higher priority). */
	priority: number;

	/** Optional suggested parameter values for the tool based on the current context. */
	suggested_inputs?: Record<string, unknown>;

	/** Alternative tools that could be used if the primary recommendation is not available. */
	alternatives?: string[];
}

/**
 * Defines an MCP tool that can be recommended and invoked.
 *
 * Tools are the basic building blocks for performing operations
 * such as reading files, running commands, or making API calls.
 *
 * @example
 * ```typescript
 * const tool: Tool = {
 *   name: 'Read',
 *   description: 'Read a file from the filesystem',
 *   inputSchema: {
 *     type: 'object',
 *     properties: {
 *       file_path: { type: 'string' }
 *     },
 *     required: ['file_path']
 *   }
 * };
 * ```
 */
export interface Tool {
	/** Unique identifier for the tool. */
	name: string;

	/** Human-readable description of what the tool does. */
	description: string;

	/** JSON Schema defining the parameters the tool accepts. */
	inputSchema: Record<string, unknown>;
}
