/**
 * Core type definitions for the CCSequentialThinkingMCP server.
 *
 * This module defines all the primary data structures used throughout the application,
 * including tool/skill recommendations, thought data, and server configuration.
 *
 * @module types
 */

/**
 * Represents a recommended MCP tool with associated metadata.
 *
 * Tool recommendations are generated by the sequential thinking process to suggest
 * appropriate tools for completing specific tasks. Each recommendation includes
 * a confidence score and rationale to help the LLM make informed decisions.
 *
 * @example
 * ```typescript
 * const recommendation: ToolRecommendation = {
 *   tool_name: 'mcp__tavily-mcp__tavily-search',
 *   confidence: 0.9,
 *   rationale: 'Best for searching current web content',
 *   priority: 1,
 *   suggested_inputs: { query: 'TypeScript documentation' },
 *   alternatives: ['mcp__web_reader__webReader']
 * };
 * ```
 */
export interface ToolRecommendation {
	/** The unique name/identifier of the recommended tool. */
	tool_name: string;

	/** Confidence score from 0-1 indicating how appropriate this tool is for the current task. */
	confidence: number;

	/** Explanation of why this tool is recommended and how it addresses the current need. */
	rationale: string;

	/** Order in the recommendation sequence (lower numbers = higher priority). */
	priority: number;

	/** Optional suggested parameter values for the tool based on the current context. */
	suggested_inputs?: Record<string, unknown>;

	/** Alternative tools that could be used if the primary recommendation is not available. */
	alternatives?: string[];
}

/**
 * Represents a recommended skill with associated metadata.
 *
 * Skills are higher-level workflows that coordinate multiple tools and operations.
 * Skill recommendations include information about which tools the skill is allowed
 * to use and whether the skill can be invoked directly by users.
 *
 * @example
 * ```typescript
 * const recommendation: SkillRecommendation = {
 *   skill_name: 'commit',
 *   confidence: 0.95,
 *   rationale: 'Handles the complete git commit workflow',
 *   priority: 1,
 *   alternatives: ['review-pr'],
 *   allowed_tools: ['Bash', 'Read', 'Grep'],
 *   user_invocable: true
 * };
 * ```
 */
export interface SkillRecommendation {
	/** The unique name/identifier of the recommended skill. */
	skill_name: string;

	/** Confidence score from 0-1 indicating how appropriate this skill is for the current task. */
	confidence: number;

	/** Explanation of why this skill is recommended and how it addresses the current need. */
	rationale: string;

	/** Order in the recommendation sequence (lower numbers = higher priority). */
	priority: number;

	/** Alternative skills that could be used if the primary recommendation is not available. */
	alternatives?: string[];

	/** List of tool names this skill is allowed to use during execution. */
	allowed_tools?: string[];

	/** Whether this skill can be directly invoked by users (via slash commands). */
	user_invocable?: boolean;
}

/**
 * Represents a coordinated step in a multi-step thought process.
 *
 * Step recommendations combine tool and skill recommendations to provide
 * a comprehensive plan for completing a specific task, including expected
 * outcomes and conditions for moving to the next step.
 *
 * @example
 * ```typescript
 * const step: StepRecommendation = {
 *   step_description: 'Search for TypeScript documentation',
 *   recommended_tools: [
 *     {
 *       tool_name: 'mcp__tavily-mcp__tavily-search',
 *       confidence: 0.9,
 *       rationale: 'Best for web search',
 *       priority: 1
 *     }
 *   ],
 *   recommended_skills: [],
 *   expected_outcome: 'Search results with TypeScript documentation links',
 *   next_step_conditions: ['If no results found, try broader search terms']
 * };
 * ```
 */
export interface StepRecommendation {
	/** Human-readable description of what needs to be done in this step. */
	step_description: string;

	/** Array of tools recommended for this step, ordered by priority. */
	recommended_tools: ToolRecommendation[];

	/** Optional array of skills recommended for this step. */
	recommended_skills?: SkillRecommendation[];

	/** Description of what to expect after completing this step. */
	expected_outcome: string;

	/** Optional conditions to consider when determining the next step. */
	next_step_conditions?: string[];
}

/**
 * Core data structure for a thought in the sequential thinking process.
 *
 * Thoughts represent individual reasoning steps that can be chained together
 * to form complex reasoning chains. Each thought can reference previous thoughts,
 * create branches, and include tool/skill recommendations.
 *
 * @remarks
 * - Thoughts are numbered sequentially within a branch
 * - Branching allows exploring alternative reasoning paths
 * - Revisions allow correcting or updating previous thoughts
 * - The `next_thought_needed` flag controls continuation
 *
 * @example
 * ```typescript
 * const thought: ThoughtData = {
 *   available_mcp_tools: ['Read', 'Write', 'Bash'],
 *   available_skills: ['commit', 'pdf'],
 *   thought: 'I should read the package.json to understand dependencies',
 *   thought_number: 1,
 *   total_thoughts: 5,
 *   next_thought_needed: true,
 *   current_step: {
 *     step_description: 'Read package.json',
 *     recommended_tools: [{
 *       tool_name: 'Read',
 *       confidence: 1.0,
 *       rationale: 'Direct file reading',
 *       priority: 1
 *     }],
 *     expected_outcome: 'Contents of package.json'
 *   }
 * };
 * ```
 */
export interface ThoughtData {
	/** Array of MCP tool names available for recommendation. */
	available_mcp_tools?: string[];

	/** Array of skill names available for recommendation. */
	available_skills?: string[];

	/** The current thinking step or reasoning content. */
	thought: string;

	/** Current thought number in the sequence (1-indexed). */
	thought_number: number;

	/** Estimated total number of thoughts (can be adjusted during processing). */
	total_thoughts: number;

	/** Whether this thought revises a previous thought. */
	is_revision?: boolean;

	/** If revising, the thought number being revised. */
	revises_thought?: number;

	/** If branching, the thought number to branch from. */
	branch_from_thought?: number;

	/** Unique identifier for the branch this thought belongs to. */
	branch_id?: string;

	/** Whether more thoughts are needed beyond the current `total_thoughts`. */
	needs_more_thoughts?: boolean;

	/** Whether another thought should be generated (required field). */
	next_thought_needed: boolean;

	/** The current step recommendation being considered. */
	current_step?: StepRecommendation;

	/** Steps that have already been recommended in previous thoughts. */
	previous_steps?: StepRecommendation[];

	/** High-level descriptions of upcoming steps yet to be recommended. */
	remaining_steps?: string[];
}

/**
 * Defines an MCP tool that can be recommended and invoked.
 *
 * Tools are the basic building blocks for performing operations
 * such as reading files, running commands, or making API calls.
 *
 * @example
 * ```typescript
 * const tool: Tool = {
 *   name: 'Read',
 *   description: 'Read a file from the filesystem',
 *   inputSchema: {
 *     type: 'object',
 *     properties: {
 *       file_path: { type: 'string' }
 *     },
 *     required: ['file_path']
 *   }
 * };
 * ```
 */
export interface Tool {
	/** Unique identifier for the tool. */
	name: string;

	/** Human-readable description of what the tool does. */
	description: string;

	/** JSON Schema defining the parameters the tool accepts. */
	inputSchema: Record<string, unknown>;
}

/**
 * Defines a skill that coordinates multiple tools and operations.
 *
 * Skills are higher-level workflows that can be invoked directly
 * by users (via slash commands) or recommended by the sequential
 * thinking process.
 *
 * @example
 * ```typescript
 * const skill: Skill = {
 *   name: 'commit',
 *   description: 'Create a git commit with proper message formatting',
 *   user_invocable: true,
 *   allowed_tools: ['Bash', 'Read', 'Grep']
 * };
 * ```
 */
export interface Skill {
	/** Unique identifier for the skill. */
	name: string;

	/** Human-readable description of what the skill does. */
	description: string;

	/** Whether users can invoke this skill directly via slash commands. */
	user_invocable?: boolean;

	/** List of tool names this skill is allowed to use. */
	allowed_tools?: string[];
}

/**
 * Runtime server configuration containing available tools and skills.
 *
 * This interface represents the active configuration at runtime,
 * providing access to the registry of available tools and skills.
 *
 * @example
 * ```typescript
 * const config: ServerConfig = {
 *   available_tools: new Map([
 *     ['Read', { name: 'Read', description: '...', inputSchema: {...} }]
 *   ]),
 *   available_skills: new Map([
 *     ['commit', { name: 'commit', description: '...', user_invocable: true }]
 *   ])
 * };
 * ```
 */
export interface ServerConfig {
	/** Map of registered tools indexed by their unique names. */
	available_tools: Map<string, Tool>;

	/** Map of registered skills indexed by their unique names. */
	available_skills: Map<string, Skill>;
}

/**
 * Interface for services that need resource cleanup.
 * Implement this on any service that holds resources (connections, file handles, timers, etc.)
 *
 * @example
 * ```typescript
 * class MyService implements IDisposable {
 *   async dispose(): Promise<void> {
 *     await this.closeConnections();
 *     this.clearTimers();
 *   }
 * }
 * ```
 */
export interface IDisposable {
	/** Release all resources held by this service. */
	dispose(): Promise<void>;
}
